name: List services in GCP
on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0'
      with:
          workload_identity_provider: 'projects/205623571289/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: ' github-actions-test@ams-pro-2022.iam.gserviceaccount.com'
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud container clusters list
