name: List services in GCP
on:
  workflow_dispatch: {}
  release:
    types: [prereleased, released]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: version
      run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
    - name: reusable workflow
      id: workflow_call
      uses: aaronschweig/gcp-workload-identity-test/.github/workflows/reusable-workflow.yaml@main
      with:
        version: ${{ steps.version.version }}-from-caller
        service: test
    - name: Print image tag
      run: echo ${{ steps.workflow_call.tag }}