name: List services in GCP
on:
  workflow_dispatch: {}
  release:
    types: [prereleased, released]

jobs:
  build-and-push:
    uses: aaronschweig/gcp-workload-identity-test/.github/workflows/reusable-workflow.yaml@main
    with:
      version: ${GITHUB_REF#refs/tags/}-from-caller
      service: test
  
  verify:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Print image tag
      run: echo ${{ needs.build-and-push.outputs.tag }}