name: List services in GCP
on:
  workflow_dispatch: {}
  release:
    types: [prereleased, released]

permissions:
  id-token: write
  contents: read

jobs:
  dockerize:
    uses: aaronschweig/gcp-workload-identity-test/.github/workflows/reusable-workflow.yaml@main
    with:
      service: test
  
  verify:
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
    - name: Print image tag
      run: echo ${{ needs.dockerize.outputs.tag }}