name: List services in GCP
on:
  workflow_dispatch: {}
  release:
    types: [prereleased, released]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0'
      with:
          workload_identity_provider: 'projects/205623571289/locations/global/workloadIdentityPools/ams-pro/providers/github-actions'
          service_account: ' github-actions-test@ams-pro-2022.iam.gserviceaccount.com'
          token_format: 'access_token'

    - uses: docker/setup-buildx-action@v2
      name: Set up Docker Buildx

    - uses: 'docker/login-action@v1'
      with:
        registry: 'europe-west3-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
  
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: europe-west3-docker.pkg.dev/ams-pro/test:${{ steps.get_version.outputs.version }}
